default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taskmanager_development

test:
  <<: *default
  database: taskmanager_test

production:
  <<: *default
  database: taskmanager_production
  username: taskmanager